const INCREMENT = "INCREMENT"
const DECREMENT = "DECREMENT"
const ADD_NUMBER = "ADD_NUMBER"
const SUB_NUMBER = "SUB_NUMBER"
const CHANGE_BANNER = "CHANGE_BANNER"
const GET_HOME_MUTIDATA = "GET_HOME_MUTIDATA"


export {
    INCREMENT,
    DECREMENT,
    ADD_NUMBER,
    SUB_NUMBER,
    CHANGE_BANNER,
    GET_HOME_MUTIDATA
}